Repository CTMobi/Wubtitle-Wordpress-Plugin, pull requests merged in 2020-07, with the labels that each got.

#215 lodash from 4.17.15 to 4.17.19
  package-lock.json
Labels: dependencies

#241 fix headers cron
  includes/Core/Cron.php
Labels: bug, urgent

#243 Alessio fix cache token time
  includes/Core/Activation.php
  includes/Dashboard/Settings.php
Labels: bug, urgent

#250 delete wubtitle_free from the cache
  includes/Dashboard/Templates/plans_array.php
Labels: bug
